
version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build1:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install express
      - run: echo "running"
      - run: node server.js

workflows:
  build-and-test:
    jobs:
      - build1
  


