
version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build-and-test:
    executor: 
      name: node/default
    steps:
      - node/install-packages:
          pkg-manager: npm
      - run: npm install
      - run: echo "done"

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master


